IBM/ai-privacy-toolkit

apt/minimization/minimizer.py, notebooks/minimization_adult.ipynb
Several fixes to minimization code + Jupyter notebook demonstrating the use of the minimization module (fixes #8 )
=> Minimization fixes

apt/minimization/README.md, apt/minimization/minimizer.py, tests/test_minimizer.py
supporting categorical features
=> Sup cat features

apt/anonymization/anonymizer.py, notebooks/membership_inference_dp_diabetes_reg.ipynb, tests/test_anonymizer.py
Support regression models for anonymization
=> Support regression models

apt/minimization/minimizer.py, tests/test_minimizer.py
support regression models for minimizing algo
=> Regression minimization

apt/anonymization/anonymizer.py, tests/test_anonymizer.py
build the DT on all features and not just QI and one-hot encoding only for categorical features
=> Build the dt on all features anon

apt/minimization/minimizer.py, tests/test_minimizer.py
Two types of encoding performed: first for target model. This encoder can be provided to the API from outside, if not provided a default encoding will be performed. Second (perhaps different) encoding for decision tree which is now consistent with the generalized values.
=> Consistent one-hot-encoding

apt/utils/datasets/datasets.py, apt/utils/models/model.py, tests/test_model.py
check if train is None in Data
In BlackboxClassifier use test if train not available
In Data handle None for train
=> Wrappers no train

apt/utils/models/__init__.py, apt/utils/models/model.py, requirements.txt, tests/test_minimizer.py, tests/test_model.py
Enable working with black-box models by supplying a predict method. 
Support probabilities as output, both for predict method and for data based method.
=> Blackbox predict method

apt/utils/models/__init__.py, apt/utils/models/model.py, apt/utils/models/sklearn_model.py, tests/test_model.py
https://github.com/IBM/ai-privacy-toolkit/issues/41
=> enhance calculation of nb classes  + tests

apt/utils/datasets/__init__.py, apt/utils/datasets/datasets.py, apt/utils/models/model.py, tests/test_datasets.py, tests/test_minimizer.py, tests/test_model.py
Data and Dataset now have an option to store model predictions (instead of or in addition to x,y).
Blackbox classifier no longer applies preprocessing to data.
=> Support additional use cases for data

apt/utils/models/__init__.py, apt/utils/models/keras_model.py, requirements.txt, tests/test_model.py
New wrapper for keras regression models.
=> Keras regression support

apt/utils/datasets/datasets.py, apt/utils/models/model.py, tests/test_model.py
Looks for predictions by default and only if they are none uses labels (for backwards compatibility).
=> BlackboxClassifier based on predictions works with DatasetWithPredictions

apt/utils/models/__init__.py, apt/utils/models/xgboost_model.py, tests/test_model.py
Currently assumes that the supplied model is pre-fit.
=> Add support for xgboost XGBClassifier (#53)

apt/utils/models/pytorch_model.py
Signed-off-by: abigailt <abigailt@il.ibm.com>
=> Add loss and optimizer to Pytorch wrapper as properties

apt/utils/models/model.py
Fix #61 
Signed-off-by: abigailt <abigailt@il.ibm.com>
=> Blackbox classifier enhancements

apt/utils/dataset_utils.py, requirements.txt, tests/test_model.py
Cleanup dependencies, fix test data location, cleanup asserts.
=> Prepare project for CI

apt/minimization/minimizer.py
Signed-off-by: abigailt <abigailt@il.ibm.com>
=> Add option for non-stratified split in minimizer

apt/minimization/minimizer.py
Signed-off-by: abigailt <abigailt@il.ibm.com>
=> Fix random state to make tests pass

.github/workflows/python-package.yml
Run Lint and PyTest on Python 3.8
Signed-off-by: Maya Anderson <mayaa@il.ibm.com>
=> Create CI test workflow using GitHub Actions

apt/utils/models/pytorch_model.py
Fix calculation of score for pytorch models when a single column of probabilities is used for binary classification.
=> Fix calculation of score for pytorch models

apt/risk/data_assessment/attack_strategy_utils.py, apt/risk/data_assessment/dataset_assessment_manager.py, apt/risk/data_assessment/dataset_attack_membership_classification.py, apt/risk/data_assessment/dataset_attack_membership_knn_probabilities.py, apt/risk/data_assessment/dataset_attack_whole_dataset_knn_distance.py, tests/test_data_assessment_short_test.py
Removed redundant if statement so all datasets are now processed as numpy.
Changed test to have a case where the dataset sent to the metrics is a dataframe.
=> Fix error with pandas dataframes
